/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_DoorController_INCLUDED
#define _EntitiesMP_DoorController_INCLUDED 1
#include <EntitiesMP/Player.h>
#include <EntitiesMP/MovingBrush.h>
extern DECL_DLL CEntityPropertyEnumType DoorType_enum;
enum DoorType {
  DT_AUTO = 0,
  DT_TRIGGERED = 1,
  DT_LOCKED = 2,
  DT_TRIGGEREDAUTO = 3,
};
DECL_DLL inline void ClearToDefault(DoorType &e) { e = (DoorType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CDoorController_DLLClass;
class CDoorController : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  CEntityPointer m_penTarget1;
  CEntityPointer m_penTarget2;
  FLOAT m_fWidth;
  FLOAT m_fHeight;
  BOOL m_bPlayersOnly;
  enum DoorType m_dtType;
  CTStringTrans m_strLockedMessage;
  CEntityPointer m_penLockedTarget;
  BOOL m_bTriggerOnAnything;
  BOOL m_bActive;
  BOOL m_bLocked;
  CEntityPointer m_penCaused;
  BOOL m_bOpened;
  INDEX m_iOpenMobNum;
  INDEX m_iMaxCheckPoint;
   
#line 59 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
CEntity * GetTarget(void)const;
   
#line 61 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
const CTString & GetDescription(void)const;
  
#line 76 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
virtual void Read_t(CTStream * istr,BOOL bNetwork);
   
#line 84 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
BOOL CanReactOnEntity(CEntity * pen);
   
#line 102 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
BOOL CanTriggerOnEntity(CEntity * pen);
   
#line 107 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
void TriggerDoor(void);
   
#line 182 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
void MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX);
   
#line 191 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
SLONG GetUsedMemory(void);
   
#line 202 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
BOOL AnyPlayerHasKey(INDEX iKey);
   
#line 217 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
void RemoveKeyFromAllPlayers(INDEX iKey);
#define  STATE_CDoorController_Main 1
  BOOL 
#line 230 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
Main(const CEntityEvent &__eeInput);
  BOOL H0x00dd0000_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd0001_Main_02(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorAuto 0x00dd0002
  BOOL 
#line 263 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorAuto(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorAutoActive 0x00dd0003
  BOOL 
#line 274 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorAutoActive(const CEntityEvent &__eeInput);
  BOOL H0x00dd0004_DoorAutoActive_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd0005_DoorAutoActive_02(const CEntityEvent &__eeInput);
  BOOL H0x00dd0006_DoorAutoActive_03(const CEntityEvent &__eeInput);
  BOOL H0x00dd0007_DoorAutoActive_04(const CEntityEvent &__eeInput);
  BOOL H0x00dd0008_DoorAutoActive_05(const CEntityEvent &__eeInput);
  BOOL H0x00dd0009_DoorAutoActive_06(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorAutoInactive 0x00dd000a
  BOOL 
#line 318 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorAutoInactive(const CEntityEvent &__eeInput);
  BOOL H0x00dd000b_DoorAutoInactive_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd000c_DoorAutoInactive_02(const CEntityEvent &__eeInput);
  BOOL H0x00dd000d_DoorAutoInactive_03(const CEntityEvent &__eeInput);
  BOOL H0x00dd000e_DoorAutoInactive_04(const CEntityEvent &__eeInput);
  BOOL H0x00dd000f_DoorAutoInactive_05(const CEntityEvent &__eeInput);
  BOOL H0x00dd0010_DoorAutoInactive_06(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorDummy 0x00dd0011
  BOOL 
#line 341 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorDummy(const CEntityEvent &__eeInput);
  BOOL H0x00dd0012_DoorDummy_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd0013_DoorDummy_02(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorTriggered 0x00dd0014
  BOOL 
#line 354 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorTriggered(const CEntityEvent &__eeInput);
  BOOL H0x00dd0015_DoorTriggered_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd0016_DoorTriggered_02(const CEntityEvent &__eeInput);
  BOOL H0x00dd0017_DoorTriggered_03(const CEntityEvent &__eeInput);
  BOOL H0x00dd0018_DoorTriggered_04(const CEntityEvent &__eeInput);
  BOOL H0x00dd0019_DoorTriggered_05(const CEntityEvent &__eeInput);
  BOOL H0x00dd001a_DoorTriggered_06(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorLocked 0x00dd001b
  BOOL 
#line 397 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorLocked(const CEntityEvent &__eeInput);
  BOOL H0x00dd001c_DoorLocked_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd001d_DoorLocked_02(const CEntityEvent &__eeInput);
  BOOL H0x00dd001e_DoorLocked_03(const CEntityEvent &__eeInput);
  BOOL H0x00dd001f_DoorLocked_04(const CEntityEvent &__eeInput);
  BOOL H0x00dd0020_DoorLocked_05(const CEntityEvent &__eeInput);
  BOOL H0x00dd0021_DoorLocked_06(const CEntityEvent &__eeInput);
#define  STATE_CDoorController_DoorTriggeredAuto 0x00dd0022
  BOOL 
#line 467 "D:/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/DoorController.es"
DoorTriggeredAuto(const CEntityEvent &__eeInput);
  BOOL H0x00dd0023_DoorTriggeredAuto_01(const CEntityEvent &__eeInput);
  BOOL H0x00dd0024_DoorTriggeredAuto_02(const CEntityEvent &__eeInput);
  BOOL H0x00dd0025_DoorTriggeredAuto_03(const CEntityEvent &__eeInput);
  BOOL H0x00dd0026_DoorTriggeredAuto_04(const CEntityEvent &__eeInput);
  BOOL H0x00dd0027_DoorTriggeredAuto_05(const CEntityEvent &__eeInput);
  BOOL H0x00dd0028_DoorTriggeredAuto_06(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_DoorController_INCLUDED
