/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_PlayerAnimator2_INCLUDED
#define _EntitiesMP_PlayerAnimator2_INCLUDED 1
#include <EntitiesMP/Player.h>
#include <EntitiesMP/PlayerWeapons.h>
#include <EntitiesMP/Enemy.h>
#include <EntitiesMP/PetBase.h>
#define EVENTCODE_EAnimatorInit 0x01960000
class DECL_DLL EAnimatorInit : public CEntityEvent {
public:
EAnimatorInit();
CEntityEvent *MakeCopy(void);
BOOL CheckIDs(void);
SLONG GetSizeOf(void);
CEntityID eidPlayer;
};
DECL_DLL inline void ClearToDefault(EAnimatorInit &e) { e = EAnimatorInit(); } ;
extern "C" DECL_DLL CDLLEntityClass CPlayerAnimator_DLLClass;
class DECL_DLL  CPlayerAnimator : public CRationalEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
   virtual void SetDefaultProperties(void);
  CEntityPointer m_penPlayer;
  BOOL m_bReference;
  FLOAT m_fLastActionTime;
  INDEX m_iContent;
  BOOL m_bWaitJumpAnim;
  BOOL m_bCrouch;
  BOOL m_iCrouchDownWait;
  BOOL m_iRiseUpWait;
  BOOL m_bChangeWeapon;
  BOOL m_bSwim;
  INDEX m_iFlare;
  INDEX m_iSecondFlare;
  BOOL m_bAttacking;
  FLOAT m_tmAttackingDue;
  FLOAT m_tmFlareAdded;
  BOOL m_bDisableAnimating;
  FLOAT3D m_vLastPlayerPosition;
  FLOAT m_fEyesYLastOffset;
  FLOAT m_fEyesYOffset;
  FLOAT m_fEyesYSpeed;
  BOOL m_bMdl;
  FLOAT m_fWeaponYLastOffset;
  FLOAT m_fWeaponYOffset;
  FLOAT m_fWeaponYSpeed;
  BOOL m_bMoving;
  FLOAT m_fMoveLastBanking;
  FLOAT m_fMoveBanking;
  BOOL m_iMovingSide;
  BOOL m_bSidestepBankingLeft;
  BOOL m_bSidestepBankingRight;
  FLOAT m_fSidestepLastBanking;
  FLOAT m_fSidestepBanking;
  INDEX m_iWeaponLast;
  FLOAT m_fBodyAnimTime;
  INDEX m_iPlayerID;
  FLOAT m_fAttack1AnimTime;
  FLOAT m_fAttack2AnimTime;
  FLOAT m_fSkill1AnimTime;
  FLOAT m_fSkill2AnimTime;
  FLOAT m_fAttack3AnimTime;
  FLOAT m_fAttack4AnimTime;
  FLOAT m_fExtAttack1AnimTime;
  FLOAT m_fExtAttack2AnimTime;
  FLOAT m_fExtAttack3AnimTime;
  FLOAT m_fExtAttack4AnimTime;
  CEntityPointer m_penPrediction;
CModelObject * pmoModel;
  
#line 471 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
virtual void InitializeFromNet();
   
#line 477 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void Read_t(CTStream * istr,BOOL bNetwork);
   
#line 482 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void Precache(void);
   
#line 488 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
CPlayer * GetPlayer(void);
   
#line 492 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
CModelObject * GetBody(void);
   
#line 500 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
CModelObject * GetBodyRen(void);
   
#line 510 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void SetComponents(CModelObject * mo,ULONG ulIDModel,ULONG ulIDTexture,
#line 511 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture);
   
#line 538 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void AddAttachmentModel(CModelObject * mo,INDEX iAttachment,ULONG ulIDModel,ULONG ulIDTexture,
#line 539 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture);
   
#line 545 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void AddWeaponAttachment(INDEX iAttachment,ULONG ulIDModel,ULONG ulIDTexture,
#line 546 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture);
   
#line 552 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void SetAttachment(INDEX iAttachment);
   
#line 807 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void SetItem(CModelObject * pmo);
   
#line 825 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void SetBodyAnimation(INDEX iAnimation,ULONG ulFlags);
   
#line 841 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void InitializeProperties(void);
   
#line 887 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void StoreLast(void);
   
#line 898 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void AnimateBanking(void);
   
#line 955 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void AnimateSoftEyes(void);
   
#line 993 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void ChangeView(CPlacement3D & pl);
   
#line 1025 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyAndHeadOrientation(CPlacement3D & plView);
   
#line 1047 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void WalkAnim();
   
#line 1109 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void RunAnim(float fRunSpeedMul);
   
#line 1172 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void PickAnim();
   
#line 1214 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void IdleAnim();
   
#line 1278 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void DamageAnim();
   
#line 1319 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void AnimatePlayer(void);
   
#line 1975 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void Rise(void);
   
#line 1991 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void Fall(void);
   
#line 2016 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void Swim(void);
   
#line 2039 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void Stand(void);
   
#line 2063 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void FireAnimation(INDEX iAnim,ULONG ulFlags);
   
#line 2106 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void FireAnimationOff(void);
   
#line 2152 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyWalkAnimation();
   
#line 2162 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyStillAnimation();
   
#line 2177 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void SetWholeAnimation(INDEX iAnimation,ULONG ulFlags,FLOAT fBlendTime,FLOAT fSpeed);
   
#line 2191 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyPushAnimation();
   
#line 2271 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyPullAnimation();
   
#line 2292 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyPullItemAnimation();
   
#line 2306 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyPickItemAnimation();
   
#line 2320 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void BodyRemoveItem();
   
#line 2332 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void OnPreRender(void);
   
#line 2353 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void ShowFlare(INDEX iAttachWeapon,INDEX iAttachObject,INDEX iAttachFlare);
   
#line 2365 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
void HideFlare(INDEX iAttachWeapon,INDEX iAttachObject,INDEX iAttachFlare);
#define  STATE_CPlayerAnimator_ReminderAction 0x01960001
  BOOL 
#line 2454 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
ReminderAction(const CEntityEvent &__eeInput);
#define  STATE_CPlayerAnimator_Main 1
  BOOL 
#line 2491 "C:/Dev/LC_2009_Project/lastchaos-source-client-2009/EntitiesMP/PlayerAnimator2.es"
Main(const CEntityEvent &__eeInput);
  BOOL H0x01960002_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01960003_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_PlayerAnimator2_INCLUDED
